# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [279]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [280]:
A = np.arange(1, 16).reshape(3,5)

In [281]:
#
print("Dimension:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)


Dimension: 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [282]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [283]:
print("Elementwise Subtraction B - C")
print(B - C)
print()
print("Elementwise Multiplication B * C")
print(B * C)
print()
print("Matrix Multiplication B @ C")
print(B @ C)

Elementwise Subtraction B - C
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication B * C
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication B @ C
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [284]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [285]:
# exponentiate each number elementwise
print(np.exp(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [286]:
# Calculate the minimum value in the matrix
print(np.min(B))

1


In [287]:
# Calculate the minimum value in each row
print(np.min(B, axis=1))

[1 4 7]


In [288]:
# Calculate the minimum value in each column
print(np.min(B, axis=0))

[1 2 3]


In [289]:
#index value matrix
print(np.argmin(B))

0


In [290]:
#index value row
print(np.argmin(B, axis=0))


[0 0 0]


In [291]:
# Calculate sum of all elements
print(np.sum(B))

45


In [292]:
# Calculate the mean for each column
print(np.mean(B, axis=0))


[4. 5. 6.]


In [293]:
# Calculate the median for each column
print(np.median(B, axis=0))

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [294]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [295]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [296]:
# It means that you slice the array based on the axes, in this case [1] = selection of what to slice from the array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [297]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [298]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [299]:
# using the flat function
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [300]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [301]:
# When B has three axes it means that the array is 3d. 2 sets of blocks, where every block has 3 x rows and 3 x columns.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [302]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [303]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [304]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [305]:
# Function to add and multiply matrices

def add_mult_matrices(matrix1, matrix2, operation):
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both matrices is not of type np.ndarray")
    
    if operation not in("add", "multiply"):
        raise ValueError("operation is not add or multiply")
    
    if operation == "add":
        if matrix1.shape != matrix2.shape:
            raise ValueError(" the matrices doesnt have the same shape")
        return matrix1 + matrix2
    
    elif operation == "multiply":
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError(" the matrices doesnt have the same rows contra columns")
        return matrix1 @ matrix2
    

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[1, 1], [5, 6]])

test_addera = add_mult_matrices(matrix1, matrix2, "add")
print(test_addera)   

test_mult = add_mult_matrices(matrix1, matrix2, "multiply")
print(test_mult) 

test_subtract = add_mult_matrices(matrix1, matrix2, "subtract")



#

[[ 2  3]
 [ 8 10]]
[[11 13]
 [23 27]]


ValueError: operation is not add or multiply

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
# Uppgift 10.1.1.

x = np.array([4,3])

# (a) Vilken dimension har vektorn x?
print("(a) Vilken dimension har vektorn x:", x.shape)

# (b) Beräkna 5x.
print("(b) Beräkna 5x:", 5*x)

# (c) Beräkna 3x.
print("(c) Beräkna 3x:", 3*x)

# (d) Beräkna 5x+3x.
print("(d) Beräkna 5x+3x:", 5*x+3*x)

# (e) Beräkna 8x.
print("(e) Beräkna 8x:", 8*x)

# (f) Beräkna 4x−x.
print("(f) Beräkna 4x−x:", 4*x-x)

# (g) Beräkna x⊤, vilken blir den nya dimensionen efter att transponeringen utförts?

transponering = x.T

print("(g) Beräkna x⊤:", transponering)
print(f"Ny dimension: {transponering.shape}")


# (h) Är x+x⊤ definierat?

print("(h) Är x+x⊤ definierat: not done")

# (i) Beräkna ∥x∥.

normen_x = np.linalg.norm(x)
print("(i) Beräkna ∥x∥:", normen_x)


In [ ]:
# Uppgift 10.1.2.

v = np.array([3, 7, 0, 11])

# (a) Vilken dimension har vektorn v?
print("(a) Vilken dimension har vektorn v:", v.shape)

# (b) Beräkna 2v
print("(b) Beräkna 2v:", 2*v_column)

# (c) Beräkna 5v + 2v.
print("(c) Beräkna 5v + 2v:", 5*v_column+2*v_column)

# (d) Beräkna 4v − 2v.
print("(d) Beräkna 4v − 2v:", 4*v_column - 2*v_column)

# (e) Beräkna v⊤, vilken blir den nya dimensionen efter att transponeringen utförts?
transponera = v_column.T

print("(e) Beräkna v⊤:", transponera)
print(f"Ny dimension: {transponera.shape}")

# (f) Beräkna ∥v∥.
normen_v = np.linalg.norm(v)
print("(f) Beräkna ∥v∥:", normen_v)


In [ ]:
# Uppgift 10.1.3

# Definiera vektorerna v1 = (4, 3, 1, 5) och v2 = (2, 3, 1, 1)
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) Beräkna ∥v1∥.

normen_v1 = np.linalg.norm(v1)
print("(a) Beräkna ∥v1∥:", normen_v1)


# (b) Beräkna ∥v1-v2∥.
normen_v2 = np.linalg.norm(v2)
print("(b) Beräkna ∥v1-v2∥:", normen_v1 - normen_v2)

# diff_v1_v2 = np.linalg.norm(v1-v2)
# print("(b) Beräkna ∥v1-v2∥:", diff_v1_v2)


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
# Uppgift 10.2.1.

# Definiera matriserna
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

# (a) Beräkna 2A:
print("(a) Beräkna 2A:", 2*A)

# (b) Beräkna B-2A:
print("(b) Beräkna B-2A:", B-2*A)

# (c) Beräkna 3C-2E:
print("(c) Beräkna 3C-2E: Ej definierat")

# (d) Beräkna 2D-3C:
print("(d) Beräkna 2D-3C:", 2*D-3*C)

# (e) Beräkna D⊤+2D:
print("(e) Beräkna D⊤+2D:", D.T+2*D)

# (f) Beräkna 2C⊤ −2D⊤:
print("(f) Beräkna 2C⊤ −2D⊤:", 2*C.T-2*D.T)

# (g) Beräkna A⊤ −B:
print("(g) Beräkna A⊤ −B: Ej definierat")

# (h) Beräkna AC
print("(h) Beräkna AC: Ej definierat")

# (i) Beräkna CD
print("(i) Beräkna CD:", C@D)

# (j) Beräkna CB
print("(j) Beräkna CB:", C@B)

# (k) Beräkna CI
print("(k) Beräkna CI:", C@I)

# (l) Beräkna AB⊤
print("(l) Beräkna ABT:", A@B.T)


In [ ]:
# Uppgift 10.2.2.

# Definiera matrisen

A = np.array([[2, 3, 4], [5, 4, 1]])

# Beräkna AAT:
print("Beräkna AAT:", A@A.T)


In [ ]:
# Uppgift 10.2.3.

# Definiera matriserna

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4,3], [0, 2]])

print(A@B)
print()
print(A@C)
print()
print(B)
print()
print(C)
print()
print(A@B == A@C)
print()
print(B == C)



### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)